language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "noiasquad"
    token:
      secure: $SONAR_TOKEN
    branches:
          - master
script:
  - sonar-scanner

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build publish sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
